name: ax
repository: https://github.com/malmi/ax

packages:
  - packages/**
  - "tests/*"

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

scripts:
  analyze:
    description: Run `dart analyze` in all packages.
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos

  build:
    description: Build all packages.
    run: |
      melos exec -c 5 -- \
        flutter build apk

  format:
    description: Format code everywhere
    run: flutter format .

  lint:
    description: Run all static analysis checks.
    run: melos analyze && melos format

  test:
    description: Run all tests.
    run: |
      melos exec -c 5 -- \
        flutter test

  clean:deep:
    description: Clean things very deeply, can be used to establish "pristine checkout" status.
    run: git clean -x -d -f -q

  qualitycheck:
    description: Run all targets generally expected in CI for a full local quality check.
    run: |
      melos clean && \
      melos bootstrap && \
      melos lint && \
      melos build && \
      melos test

  # Additional cleanup lifecycle script, executed when `melos clean` is run.
  postclean: >
    melos exec -c 6 -- "flutter clean"

ide:
  intellij:
    enabled: false
