name: ax
description: Poor folk's version of actors for a nice state management that is more event-driven and should be used if you are an advocate of event sourcing.
version: 0.0.2
repository: https://github.com/malmi/ax

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  rxdart: ^0.28.0
  rxdart_ext: ^0.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

topics:
  - state-management
  - event-driven
  - actor
